### ISSUE TITLE
BUG - Jolly Roger Bay Walls alpha

### ISSUE THREAD

**Issue by mkst** [mkst/sm64-port#3]
The tops of the walls should be transparent.

3DS:
![image](https://user-images.githubusercontent.com/22226349/90620304-2f56f600-e20a-11ea-84db-2ec2e0a9c4e6.png)

N64:
**TODO**

> *"It's an alphacompare"* - Fazana.

More info to be added as it's discovered.

**Edit 1**

Increasing the threshold for alpha affects this:

```c
    if (cc_features.opt_texture_edge && cc_features.opt_alpha)
        C3D_AlphaTest(true, GPU_GREATER, 77); // screenshot below is with this set to 200
    else
        C3D_AlphaTest(true, GPU_GREATER, 0);
```
![image](https://user-images.githubusercontent.com/22226349/90905931-cbc6f700-e3c8-11ea-817d-9c076a1d17be.png)

**Comment by ryotoko** [comment]
Just noticed this. It's simulated fog, right? The walls are supposed to be darker (until you get close enough) but the sky portion is supposed to be completely clear, right?

**Comment by mkst** [comment]
> Just noticed this. It's simulated fog, right? The walls are supposed to be darker (until you get close enough) but the sky portion is supposed to be completely clear, right?
> 
> Edit: Somehow I remember there being a clearly visible alpha plane like this, but I guess that is also wrong

I guess I should fire up SM64 in an emulator to see how things are meant to look*; it's been a while.

Currently fog is implemented by drawing the triangles twice, once with colour, once as fog. citro3d has some [fog](https://github.com/devkitPro/citro3d/blob/master/include/c3d/fog.h) functionality which might yield better results (and performance?) if I (or someone) figures it out.

**Comment by ryotoko** [comment]
Can't find footage from an actual N64, but according to the latest paraLLEl core, that fog "wall" definitely shouldn't be there.

I've noticed some other alpha problems that are probably related to the same logic:
![2020-09-18_10-21-31 536_top_right](https://user-images.githubusercontent.com/68757712/93632582-67389100-f9a2-11ea-90ae-23fce228bc02.png)
![2020-09-18_10-41-29 412_top](https://user-images.githubusercontent.com/68757712/93632585-6a338180-f9a2-11ea-9533-a02127bfdc69.png)
The original wasn't applying a bilinear filter on the edges of textures like this, but it seems there's a different type of conflict here whenever 2 or more alpha layers are overlapping, be they shadows, water or another texture with alpha properties

![2020-09-18_10-41-51 528_top_right](https://user-images.githubusercontent.com/68757712/93632751-b7afee80-f9a2-11ea-93a1-15639486d05f.png)
It is really wonky, as sometimes it behaves as expected. This texture is calculating alpha correctly on the right side but incorrectly on the left.

**Comment by ryotoko** [comment]
I read up about alpha tests and this is my understanding:
This condition triggers when the shader is processing an alpha layer and a hard edge texture with alpha for the same texel at the same time. A shadow and a tree, for example, or in the case of JRB, the fog and the crag tops. The alpha test then calculates, based on how this function is set, all texels with combined alpha values less than 77 (of 255) and culls them. That is where the visible fog gradient (the fog "wall" as I was calling it) is coming from. Alpha values above 77 remain, so you get the darker fog in the distance, but the thinner fog in the foreground has been culled, which is incorrect. 

There is likely also a depth test, which I suspect is what's screwing the trees up in combination with an alpha test somewhere, that basically functions based on the Z buffer position instead of alpha level. The correct function is bound to be loads more nuanced, this looks like something someone was writing and then stopped half way.

**Comment by ryotoko** [comment]
This is an issue with the fog branch only:
![2020-09-25_17-21-37 251_top](https://user-images.githubusercontent.com/68757712/94325587-f2da9080-ff53-11ea-92e0-e216fa69b146.png)
I guess your fog function is not respecting the parameters of the RDP's scissoring and/or viewport? Probably the only place in the game where it happens, JRB is too dark to notice it, but you never know when these underlying issues crop up somewhere else as a glitch.

Also, a potential hint: Enabling 3D removes the fog from the scene, just like JRB fog disappears, but the credits background color change does NOT disappear. Seems to suggest you might be right with your fog being rendered at very high Z levels, so it's being clipped.

**Comment by mkst** [comment]
> This is an issue with the fog branch only:
> ![2020-09-25_17-21-37 251_top](https://user-images.githubusercontent.com/68757712/94325587-f2da9080-ff53-11ea-92e0-e216fa69b146.png)

I've just rebased `3ds-fog` off of `3ds-port` and beaten the game, TTC credits looked correct for me:

![image](https://user-images.githubusercontent.com/22226349/94370871-69a99200-00ea-11eb-827d-e741b78185d9.png)

... no closer to solving Fog + 3D as yet.
